# Generated by Django 5.0.1 on 2024-01-09 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_customer_created_customer_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cart",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="store.cart"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.FloatField(),
        ),
    ]
