# Generated by Django 5.0.1 on 2024-01-09 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_order_cart_alter_order_total_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="url",
        ),
        migrations.AddField(
            model_name="image",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="image",
            field=models.ImageField(default=None, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="image",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="store.product",
            ),
            preserve_default=False,
        ),
    ]
