# Generated by Django 5.0.1 on 2024-01-09 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_remove_image_url_image_description_image_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="store.customer",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="store.category",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="store.customer",
            ),
            preserve_default=False,
        ),
    ]
