# Generated by Django 5.0.1 on 2024-01-11 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_remove_product_parameters_category_parent_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="category",
        ),
        migrations.RemoveField(
            model_name="image",
            name="product",
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.image",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="product_image", to="store.image"
            ),
        ),
    ]
