# Generated by Django 5.0.1 on 2024-01-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_alter_category_parent_category_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(default=None, upload_to="static/store/images/"),
        ),
    ]
