# Generated by Django 5.0.1 on 2024-01-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_alter_image_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(default=None, upload_to="static/images/"),
        ),
    ]
