# Generated by Django 4.2.7 on 2024-01-23 13:10

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0019_product_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="JPEG",
                keep_meta=True,
                quality=75,
                scale=0.5,
                size=[50, 50],
                upload_to="static/images",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                default=None,
                force_format="JPEG",
                keep_meta=True,
                quality=75,
                scale=0.5,
                size=[400, 400],
                upload_to="static/images/",
            ),
        ),
    ]
