# Generated by Django 4.2.7 on 2024-01-25 12:56

from django.db import migrations, models
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0021_remove_product_brand_alter_category_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(default=django.utils.timezone.now, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="JPEG",
                keep_meta=True,
                quality=75,
                scale=0.5,
                size=[50, 50],
                upload_to="static/images",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                default=None,
                force_format="JPEG",
                keep_meta=True,
                quality=75,
                scale=0.5,
                size=[400, 400],
                upload_to="static/images/",
            ),
        ),
    ]
