# Generated by Django 4.2.7 on 2024-01-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_profile_options_alter_profile_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="avatars/default_avatar.webp", null=True, upload_to="avatars/"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Muž"), ("F", "Žena"), ("O", "Ostatní")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="title",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
