# Generated by Django 4.2.7 on 2024-01-25 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_profile_avatar"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
