# Generated by Django 4.2.7 on 2024-01-29 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
